Gisell Tatiana Hernández

In [1]:
#Importar las librerias
import requests
import pandas as pd
import datetime as dt
import io

EXTRACCIÓN

In [2]:
#Traer datos
urlData = requests.get('https://datos.gov.co/resource/7cci-nqqb.json')
#Convertir la respuesta a formato JSON
jsonData = urlData.json()
#Crear un DataFrame a partir de los datos JSON
data = pd.DataFrame(jsonData)
pd.set_option('display.max_columns', None)
# Ahora 'df' contiene los datos en forma de DataFrame
#print(data)
data

,orden,fecha,a_o,mes,d_a,gravedad,peaton,automovil,campaero,camioneta,micro,buseta,bus,camion,volqueta,moto,bicicleta,otro,via_1,barrio,hora,entidad,nombrecomuna,propietario_de_veh_culo,diurnio_nocturno,hora_restriccion_moto
0,1,01/01/2012,2012,01. Enero,07. Domingo,Con Heridos,0,1,0,0,0,0,0,0,0,0,0,0,CALLE,Mutis,12:15:00 p. m.,AGENTES DTB,17. MUTIS,Particular,Diurno,No aplica
1,2,01/01/2012,2012,01. Enero,07. Domingo,Solo Daños,0,1,0,1,0,0,0,0,0,0,0,0,VIA MATANZA,Regaderos Norte,02:00:00 p. m.,AGENTES DTB,02. NORORIENTAL,Empresa,Diurno,No aplica
2,3,01/01/2012,2012,01. Enero,07. Domingo,Solo Daños,0,0,0,1,0,0,0,0,0,0,0,0,CARRERA,Cabecera del Llano,12:00:00 p. m.,AGENTES DTB,12. CABECERA DEL LLANO,Particular,Diurno,No aplica
3,4,01/01/2012,2012,01. Enero,07. Domingo,Solo Daños,0,1,0,1,0,0,0,0,0,0,0,0,CARRERA,Norte Bajo,06:30:00 p. m.,AGENTES DTB,03. SAN FRANCISCO,Particular,Nocturno,No aplica
4,5,01/01/2012,2012,01. Enero,07. Domingo,Con Heridos,1,0,0,0,0,0,0,0,0,1,0,0,CARRERA,Dangond,12:30:00 a. m.,AGENTES DTB,11. SUR,Particular,Nocturno,En restricción
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,24/03/2012,2012,03. Marzo,06. Sabado,Solo Daños,0,1,1,0,0,0,0,0,0,0,0,0,AVENIDA GONZALEZ VALENCIA,Sotomayor,08:40:00 a. m.,AGENTES DTB,12. CABECERA DEL LLANO,Empresa,Diurno,No aplica
996,997,24/03/2012,2012,03. Marzo,06. Sabado,Con Heridos,0,1,0,0,0,0,0,0,0,1,0,0,CALLE,La Victoria,12:45:00 p. m.,AGENTES DTB,06. LA CONCORDIA,Particular,Diurno,Sin restricción
997,998,25/03/2012,2012,03. Marzo,07. Domingo,Con Heridos,0,0,0,0,0,0,0,0,0,1,0,0,AVENIDA Q SECA,Centro,12:28:00 a. m.,AGENTES DTB,15. CENTRO,Particular,Nocturno,En restricción
998,999,25/03/2012,2012,03. Marzo,07. Domingo,Con Heridos,0,0,1,0,0,0,0,0,0,1,0,0,CARRERA,El Prado,08:00:00 a. m.,AGENTES DTB,13. ORIENTAL,Particular,Diurno,Sin restricción
999,1000,25/03/2012,2012,03. Marzo,07. Domingo,Solo Daños,0,0,0,0,0,1,1,0,0,0,0,0,CALLE,San Francisco,11:00:00 a. m.,AGENTES DTB,03. SAN FRANCISCO,Empresa,Diurno,No aplica

LIMPIEZA

In [3]:
#Eliminar columnas de año, mes y día ya que ya tenemos una columna fecha
data = data.drop(['a_o', 'mes', 'd_a'], axis=1)
#Renombrar la columna "campaero" por estar mal escrita
data.rename(columns={'campaero':'campero'}, inplace=True)
#Datos
data

,orden,fecha,gravedad,peaton,automovil,campero,camioneta,micro,buseta,bus,camion,volqueta,moto,bicicleta,otro,via_1,barrio,hora,entidad,nombrecomuna,propietario_de_veh_culo,diurnio_nocturno,hora_restriccion_moto
0,1,01/01/2012,Con Heridos,0,1,0,0,0,0,0,0,0,0,0,0,CALLE,Mutis,12:15:00 p. m.,AGENTES DTB,17. MUTIS,Particular,Diurno,No aplica
1,2,01/01/2012,Solo Daños,0,1,0,1,0,0,0,0,0,0,0,0,VIA MATANZA,Regaderos Norte,02:00:00 p. m.,AGENTES DTB,02. NORORIENTAL,Empresa,Diurno,No aplica
2,3,01/01/2012,Solo Daños,0,0,0,1,0,0,0,0,0,0,0,0,CARRERA,Cabecera del Llano,12:00:00 p. m.,AGENTES DTB,12. CABECERA DEL LLANO,Particular,Diurno,No aplica
3,4,01/01/2012,Solo Daños,0,1,0,1,0,0,0,0,0,0,0,0,CARRERA,Norte Bajo,06:30:00 p. m.,AGENTES DTB,03. SAN FRANCISCO,Particular,Nocturno,No aplica
4,5,01/01/2012,Con Heridos,1,0,0,0,0,0,0,0,0,1,0,0,CARRERA,Dangond,12:30:00 a. m.,AGENTES DTB,11. SUR,Particular,Nocturno,En restricción
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,24/03/2012,Solo Daños,0,1,1,0,0,0,0,0,0,0,0,0,AVENIDA GONZALEZ VALENCIA,Sotomayor,08:40:00 a. m.,AGENTES DTB,12. CABECERA DEL LLANO,Empresa,Diurno,No aplica
996,997,24/03/2012,Con Heridos,0,1,0,0,0,0,0,0,0,1,0,0,CALLE,La Victoria,12:45:00 p. m.,AGENTES DTB,06. LA CONCORDIA,Particular,Diurno,Sin restricción
997,998,25/03/2012,Con Heridos,0,0,0,0,0,0,0,0,0,1,0,0,AVENIDA Q SECA,Centro,12:28:00 a. m.,AGENTES DTB,15. CENTRO,Particular,Nocturno,En restricción
998,999,25/03/2012,Con Heridos,0,0,1,0,0,0,0,0,0,1,0,0,CARRERA,El Prado,08:00:00 a. m.,AGENTES DTB,13. ORIENTAL,Particular,Diurno,Sin restricción
999,1000,25/03/2012,Solo Daños,0,0,0,0,0,1,1,0,0,0,0,0,CALLE,San Francisco,11:00:00 a. m.,AGENTES DTB,03. SAN FRANCISCO,Empresa,Diurno,No aplica

In [4]:
data.dtypes

orden                      object
fecha                      object
gravedad                   object
peaton                     object
automovil                  object
campero                    object
camioneta                  object
micro                      object
buseta                     object
bus                        object
camion                     object
volqueta                   object
moto                       object
bicicleta                  object
otro                       object
via_1                      object
barrio                     object
hora                       object
entidad                    object
nombrecomuna               object
propietario_de_veh_culo    object
diurnio_nocturno           object
hora_restriccion_moto      object
dtype: object

In [26]:
#Manejo de columna fecha y hora
#dt.datetime.strptime(data['fecha'], "%d/%m/%Y")

In [5]:
data = data.astype({'orden': 'int', 'fecha': 'object', 'peaton': 'int', 'automovil': 'int', 'campero': 'int', 'camioneta': 'int', 'micro': 'int', 'buseta': 'int', 'bus': 'int', 'camion': 'int', 'volqueta': 'int', 'moto': 'int', 'bicicleta': 'int', 'otro': 'int',  })
data.dtypes

orden                       int32
fecha                      object
gravedad                   object
peaton                      int32
automovil                   int32
campero                     int32
camioneta                   int32
micro                       int32
buseta                      int32
bus                         int32
camion                      int32
volqueta                    int32
moto                        int32
bicicleta                   int32
otro                        int32
via_1                      object
barrio                     object
hora                       object
entidad                    object
nombrecomuna               object
propietario_de_veh_culo    object
diurnio_nocturno           object
hora_restriccion_moto      object
dtype: object

TRANSFORMACIÓN

In [10]:
#Para llevar un orden a los datos, usaremos Orden como valor de guia

guia = 'orden'

#Divir en cuatro DataFrames, cada uno con columnas separadas

principal = data[['fecha', 'gravedad', 'entidad', 'propietario_de_veh_culo', guia]].copy()
agente_vial = data[['peaton', 'automovil', 'campero', 'camioneta', 'micro', 'buseta', 'bus', 'camion', 'volqueta', 'moto', 'bicicleta', 'otro', guia]].copy()
lugar = data[['via_1', 'barrio', 'nombrecomuna', guia]].copy()
tiempo = data[['hora', 'diurnio_nocturno', 'hora_restriccion_moto']].copy()

print("Principal:")
print(principal)

print("\nAgente vial:")
print(agente_vial)

print("\nLugar:")
print(lugar)

print("\nTiempo:")
print(tiempo)

Principal:
          fecha     gravedad      entidad propietario_de_veh_culo  orden
0    01/01/2012  Con Heridos  AGENTES DTB              Particular      1
1    01/01/2012   Solo Daños  AGENTES DTB                 Empresa      2
2    01/01/2012   Solo Daños  AGENTES DTB              Particular      3
3    01/01/2012   Solo Daños  AGENTES DTB              Particular      4
4    01/01/2012  Con Heridos  AGENTES DTB              Particular      5
..          ...          ...          ...                     ...    ...
995  24/03/2012   Solo Daños  AGENTES DTB                 Empresa    996
996  24/03/2012  Con Heridos  AGENTES DTB              Particular    997
997  25/03/2012  Con Heridos  AGENTES DTB              Particular    998
998  25/03/2012  Con Heridos  AGENTES DTB              Particular    999
999  25/03/2012   Solo Daños  AGENTES DTB                 Empresa   1000

[1000 rows x 5 columns]

Agente vial:
     peaton  automovil  campero  camioneta  micro  buseta  bus  camion  \
0         0          1        0          0      0       0    0       0
1         0          1        0          1      0       0    0       0
2         0          0        0          1      0       0    0       0
3         0          1        0          1      0       0    0       0
4         1          0        0          0      0       0    0       0
..      ...        ...      ...        ...    ...     ...  ...     ...
995       0          1        1          0      0       0    0       0
996       0          1        0          0      0       0    0       0
997       0          0        0          0      0       0    0       0
998       0          0        1          0      0       0    0       0
999       0          0        0          0      0       1    1       0

     volqueta  moto  bicicleta  otro  orden
0           0     0          0     0      1
1           0     0          0     0      2
2           0     0          0     0      3
3           0     0          0     0      4
4           0     1          0     0      5
..        ...   ...        ...   ...    ...
995         0     0          0     0    996
996         0     1          0     0    997
997         0     1          0     0    998
998         0     1          0     0    999
999         0     0          0     0   1000

[1000 rows x 13 columns]

Lugar:
                          via_1              barrio            nombrecomuna  \
0                         CALLE               Mutis               17. MUTIS
1                   VIA MATANZA     Regaderos Norte         02. NORORIENTAL
2                       CARRERA  Cabecera del Llano  12. CABECERA DEL LLANO
3                       CARRERA          Norte Bajo       03. SAN FRANCISCO
4                       CARRERA             Dangond                 11. SUR
..                          ...                 ...                     ...
995  AVENIDA  GONZALEZ VALENCIA           Sotomayor  12. CABECERA DEL LLANO
996                       CALLE         La Victoria        06. LA CONCORDIA
997              AVENIDA Q SECA              Centro              15. CENTRO
998                     CARRERA            El Prado            13. ORIENTAL
999                       CALLE       San Francisco       03. SAN FRANCISCO

     orden
0        1
1        2
2        3
3        4
4        5
..     ...
995    996
996    997
997    998
998    999
999   1000

[1000 rows x 4 columns]

Tiempo:
               hora diurnio_nocturno hora_restriccion_moto
0    12:15:00 p. m.           Diurno             No aplica
1    02:00:00 p. m.           Diurno             No aplica
2    12:00:00 p. m.           Diurno             No aplica
3    06:30:00 p. m.         Nocturno             No aplica
4    12:30:00 a. m.         Nocturno        En restricción
..              ...              ...                   ...
995  08:40:00 a. m.           Diurno             No aplica
996  12:45:00 p. m.           Diurno       Sin restricción
997  12:28:00 a. m.         Nocturno        En restricción
998  08:00:00 a. m.           Diurno       Sin restricción
999  11:00:00 a. m.           Diurno             No aplica

[1000 rows x 3 columns]

In [14]:
principal

          fecha     gravedad      entidad propietario_de_veh_culo  orden
0    01/01/2012  Con Heridos  AGENTES DTB              Particular      1
1    01/01/2012   Solo Daños  AGENTES DTB                 Empresa      2
2    01/01/2012   Solo Daños  AGENTES DTB              Particular      3
3    01/01/2012   Solo Daños  AGENTES DTB              Particular      4
4    01/01/2012  Con Heridos  AGENTES DTB              Particular      5
..          ...          ...          ...                     ...    ...
995  24/03/2012   Solo Daños  AGENTES DTB                 Empresa    996
996  24/03/2012  Con Heridos  AGENTES DTB              Particular    997
997  25/03/2012  Con Heridos  AGENTES DTB              Particular    998
998  25/03/2012  Con Heridos  AGENTES DTB              Particular    999
999  25/03/2012   Solo Daños  AGENTES DTB                 Empresa   1000

[1000 rows x 5 columns]

In [15]:
agente_vial

,peaton,automovil,campero,camioneta,micro,buseta,bus,camion,volqueta,moto,bicicleta,otro,orden
0,0,1,0,0,0,0,0,0,0,0,0,0,1
1,0,1,0,1,0,0,0,0,0,0,0,0,2
2,0,0,0,1,0,0,0,0,0,0,0,0,3
3,0,1,0,1,0,0,0,0,0,0,0,0,4
4,1,0,0,0,0,0,0,0,0,1,0,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0,1,1,0,0,0,0,0,0,0,0,0,996
996,0,1,0,0,0,0,0,0,0,1,0,0,997
997,0,0,0,0,0,0,0,0,0,1,0,0,998
998,0,0,1,0,0,0,0,0,0,1,0,0,999
999,0,0,0,0,0,1,1,0,0,0,0,0,1000

In [16]:
lugar

,via_1,barrio,nombrecomuna,orden
0,CALLE,Mutis,17. MUTIS,1
1,VIA MATANZA,Regaderos Norte,02. NORORIENTAL,2
2,CARRERA,Cabecera del Llano,12. CABECERA DEL LLANO,3
3,CARRERA,Norte Bajo,03. SAN FRANCISCO,4
4,CARRERA,Dangond,11. SUR,5
...,...,...,...,...
995,AVENIDA GONZALEZ VALENCIA,Sotomayor,12. CABECERA DEL LLANO,996
996,CALLE,La Victoria,06. LA CONCORDIA,997
997,AVENIDA Q SECA,Centro,15. CENTRO,998
998,CARRERA,El Prado,13. ORIENTAL,999
999,CALLE,San Francisco,03. SAN FRANCISCO,1000

In [17]:
tiempo

               hora diurnio_nocturno hora_restriccion_moto
0    12:15:00 p. m.           Diurno             No aplica
1    02:00:00 p. m.           Diurno             No aplica
2    12:00:00 p. m.           Diurno             No aplica
3    06:30:00 p. m.         Nocturno             No aplica
4    12:30:00 a. m.         Nocturno        En restricción
..              ...              ...                   ...
995  08:40:00 a. m.           Diurno             No aplica
996  12:45:00 p. m.           Diurno       Sin restricción
997  12:28:00 a. m.         Nocturno        En restricción
998  08:00:00 a. m.           Diurno       Sin restricción
999  11:00:00 a. m.           Diurno             No aplica

[1000 rows x 3 columns]